### ISSUE TITLE
Return server connection status

### ISSUE THREAD

**Issue by lesaff** [ServerPilot/API#10]
It would be great if the `GET /servers` returns the connection status of any given server. A `true/false` would suffice.

Thx

**Comment by clintre** [comment]
Agree, even something simple like that would be a big deal.

**Comment by jsamuel** [comment]
The `lastconn` field of the server info available from our API will tell you the time the server was last connected to ServerPilot. It's provided as a Unix timestamp.

To account for any time differences on various machines including the one you're accessing the API from, you should check whether the `lastconn` time is within about ten minutes (600 seconds) of the current time. If it is, you can consider your server to be currently connected.

That is (in pseudocode):

```
is_connected = current_timestamp - lastconn < 600
```
