### ISSUE TITLE
Provide wordpress installation  from API

### ISSUE THREAD

**Issue by insspb** [ServerPilot/API#11]
I read documentation but this seems to be impossible now.
Will it be possible in future?

**Comment by jsamuel** [comment]
Hi, we're strongly considering adding our WordPress installer to our API. We want to make sure we don't need to make any changes to this API after it's launched, so we're waiting a bit longer before getting too serious about this.

**Comment by dmhendricks** [comment]
I very much second this request. It would make automated installs of WordPress much easier. Thank you.

**Comment by TheDutchCoder** [comment]
I support this request, would make automation for WP a little easier.

**Comment by zerofill** [comment]
Definitely would like to see this added. ;)

**Comment by Thunderlab** [comment]
This is an essential feature!

**Comment by viktorix** [comment]
+1 on this. Any updates?

**Comment by jsamuel** [comment]
We've now added this to the API and the API documentation is updated with examples.

**Comment by zerofill** [comment]
OH SHIT! That friggin rocks!

Good deal man!


On 5/6/2016 2:44 PM, Justin Samuel wrote:
>
> We've now added this to the API and the API documentation is updated 
> with examples.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/ServerPilot/API/issues/11#issuecomment-217526150>
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus
