### ISSUE TITLE
Question: Formatting SSL keys

### ISSUE THREAD

**Issue by Daronspence** [ServerPilot/API#13]
When adding an  SSL cert, how should the keys be formatted when passed via cURL?

I tried passing it with `\n`s at the end of each line but that threw a JSON error, and it seems passing the file from reading it in bash wasn't working either. 

```bash
#!/bin/bash

CLIENTID='cid_MYCID'
APIKEY='MYAPIKEY'
APPID='MYAPPID'

CERT=`head -100 /etc/letsencrypt/live/daronspence.com/cert.pem`
KEY=`head -50 /etc/letsencrypt/live/daronspence.com/privkey.pem`

BODY='{"key":"'$KEY'", "cert": "'$CERT'", "cacerts": null}'

OUT=`curl https://api.serverpilot.io/v1/apps/$APPID/ssl -u $CLIENTID:$APIKEY -H "Content-Type: application/json" -d "$BODY"`

echo $OUT
```

The code above is exactly what's in my bash script, but it returns some weird stuff that's not super helpful.

So I'm guessing my formatting is wrong. I submitted a support ticket, but I'm posting here in hopes that someone watching the repo may be able to help!

**Comment by jsamuel** [comment]
I'm sorry our bash example for SSL didn't work well. We've replaced that example with a PHP example. Thanks for letting us know!
