### ISSUE TITLE
Can't Specify A Server For An App

### ISSUE THREAD

**Issue by joeinnes** [ServerPilot/API#16]
As far as I can tell, if you have multiple servers configured, you can't choose which server to create an app on. 

Could you perhaps provide some insight on how the server is chosen, and consider adding this as an option to your API?

**Comment by jsamuel** [comment]
Hi Joe,

In the API call to create an app, you have to specify the `systemuserid` which is what will determine which server the app is on and which system user it runs under. Note that `systemuserid` isn't a name like "serverpilot" that can exist on multiple servers. Instead, it's a unique identifier that identifies a particular system user on a particular server.

You can find out the ID of each system user along with which server the system user is on with the API call to list system users.

**Comment by joeinnes** [comment]
Thanks for the help!
