### ISSUE TITLE
API turn on/off AutoSSL?

### ISSUE THREAD

**Issue by dubcanada** [ServerPilot/API#17]
Hello,

Is there a way to manage AutoSSL via the API?

Thanks

**Comment by jsamuel** [comment]
Hi. Not yet, but that's definitely something we're considering.

**Comment by tylerdigital** [comment]
I'd love to see this too, any update/eta on this item?

**Comment by MikeGillihan** [comment]
This would be extremely handy.

**Comment by viktorix** [comment]
A must!

**Comment by zerofill** [comment]
I 5th, 6th, and 7th this motion! ;)

**Comment by jsamuel** [comment]
We've now added AutoSSL management to the API and the API documentation is updated.

We also added ForceSSL management (redirection from HTTP to HTTPS) to the API.
