### ISSUE TITLE
Access API via JS

### ISSUE THREAD

**Issue by Daronspence** [ServerPilot/API#30]
I'm trying to write a JS SPA to interact with the API but I'm running into CORS issues. Is the API server configured to reject browser connections? 

I'm wondering if this is my inexperience talking, but it seems like everything should be working. Here's the error I'm seeing:

"XMLHttpRequest cannot load https://api.serverpilot.io/v1/sysusers. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://craftdemo.dev' is therefore not allowed access. The response had HTTP status code 405."

**Comment by jsamuel** [comment]
Our API doesn't currently support CORS so you won't be able to directly use the ServerPilot API through JavaScript in your browser.

If you have a use case where it's safe to be giving direct access to your account's API key to JavaScript in the browser (for security reasons that would be something you don't want to do in many cases), then you could work around the fact that our API doesn't support CORS by creating a API proxy of your own that supports CORS.

For example, you could create an app with a domain such as "api.yourdomain.com" and put the following in its .htaccess file:

    RewriteRule v1/(.*) https://api.serverpilot.io/v1/$1 [P]
    Header add "Access-Control-Allow-Origin" "*"

That will cause all API requests that start with a valid URL prefix ("v1") to be proxied through to the ServerPilot API server and a CORS header allowing all domains to be added to all responses.

You then need to tell Apache it's ok to make SSL requests when proxying, so create a file at:

    /etc/apache-sp/vhosts.d/APPNAME.d/sslproxyengine.conf

with the contents:

    SSLProxyEngine on

and restart Apache with:

    sudo service apache-sp restart

I hope that helps.
